# Generated by `VIBEKE_UPDATE_CLIENTS=1 cargo test -p vibeke --test api_clients` from the schema registry (crates/vk-server/src/api_schema.rs). Do not edit.
from __future__ import annotations

from typing import Any, Dict, Optional

from . import types_gen as t


class Api:
    """One typed coroutine per control-API method (`pane.split` -> `pane_split`)."""

    async def call(
        self, method: str, params: Optional[Dict[str, Any]] = None, *, timeout: Optional[float] = None
    ) -> Any:
        raise NotImplementedError

    async def adapter_delivery_ack(self, params: "t.AdapterDeliveryAckParams") -> "t.AdapterDeliveryAckResult":
        return await self.call("adapter.delivery_ack", params)  # type: ignore[arg-type, return-value]

    async def adapter_gate(self, params: "t.AdapterGateParams") -> "t.AdapterGateResult":
        return await self.call("adapter.gate", params)  # type: ignore[arg-type, return-value]

    async def adapter_report_self(self, params: "t.AdapterReportSelfParams") -> "t.AdapterReportSelfResult":
        return await self.call("adapter.report_self", params)  # type: ignore[arg-type, return-value]

    async def adapter_signal(self, params: "t.AdapterSignalParams") -> "t.AdapterSignalResult":
        return await self.call("adapter.signal", params)  # type: ignore[arg-type, return-value]

    async def agent_get(self, params: "t.AgentGetParams") -> "t.AgentGetResult":
        return await self.call("agent.get", params)  # type: ignore[arg-type, return-value]

    async def agent_harnesses(self, params: "Optional[t.AgentHarnessesParams]" = None) -> "t.AgentHarnessesResult":
        return await self.call("agent.harnesses", params or {})  # type: ignore[arg-type, return-value]

    async def agent_interrupt(self, params: "t.AgentInterruptParams") -> "t.AgentInterruptResult":
        return await self.call("agent.interrupt", params)  # type: ignore[arg-type, return-value]

    async def agent_list(self, params: "Optional[t.AgentListParams]" = None) -> "t.AgentListResult":
        return await self.call("agent.list", params or {})  # type: ignore[arg-type, return-value]

    async def agent_manifests(self, params: "Optional[t.AgentManifestsParams]" = None) -> "t.AgentManifestsResult":
        return await self.call("agent.manifests", params or {})  # type: ignore[arg-type, return-value]

    async def agent_manifests_reload(self, params: "Optional[t.AgentManifestsReloadParams]" = None) -> "t.AgentManifestsReloadResult":
        return await self.call("agent.manifests_reload", params or {})  # type: ignore[arg-type, return-value]

    async def agent_prompt(self, params: "t.AgentPromptParams") -> "t.AgentPromptResult":
        return await self.call("agent.prompt", params)  # type: ignore[arg-type, return-value]

    async def agent_read(self, params: "t.AgentReadParams") -> "t.AgentReadResult":
        return await self.call("agent.read", params)  # type: ignore[arg-type, return-value]

    async def agent_release(self, params: "t.AgentReleaseParams") -> "t.AgentReleaseResult":
        return await self.call("agent.release", params)  # type: ignore[arg-type, return-value]

    async def agent_rename(self, params: "t.AgentRenameParams") -> "t.AgentRenameResult":
        return await self.call("agent.rename", params)  # type: ignore[arg-type, return-value]

    async def agent_report(self, params: "t.AgentReportParams") -> "t.AgentReportResult":
        return await self.call("agent.report", params)  # type: ignore[arg-type, return-value]

    async def agent_resumable(self, params: "Optional[t.AgentResumableParams]" = None) -> "t.AgentResumableResult":
        return await self.call("agent.resumable", params or {})  # type: ignore[arg-type, return-value]

    async def agent_resume(self, params: "t.AgentResumeParams") -> "t.AgentResumeResult":
        return await self.call("agent.resume", params)  # type: ignore[arg-type, return-value]

    async def agent_send_keys(self, params: "t.AgentSendKeysParams") -> "t.AgentSendKeysResult":
        return await self.call("agent.send_keys", params)  # type: ignore[arg-type, return-value]

    async def agent_spawn(self, params: "t.AgentSpawnParams") -> "t.AgentSpawnResult":
        return await self.call("agent.spawn", params)  # type: ignore[arg-type, return-value]

    async def agent_start(self, params: "t.AgentStartParams") -> "t.AgentStartResult":
        return await self.call("agent.start", params)  # type: ignore[arg-type, return-value]

    async def agent_wait(self, params: "t.AgentWaitParams") -> "t.AgentWaitResult":
        return await self.call("agent.wait", params)  # type: ignore[arg-type, return-value]

    async def api_methods(self, params: "Optional[t.ApiMethodsParams]" = None) -> "t.ApiMethodsResult":
        return await self.call("api.methods", params or {})  # type: ignore[arg-type, return-value]

    async def api_schema(self, params: "Optional[t.ApiSchemaParams]" = None) -> "t.ApiSchemaResult":
        return await self.call("api.schema", params or {})  # type: ignore[arg-type, return-value]

    async def assistant_cancel(self, params: "t.AssistantCancelParams") -> "t.AssistantCancelResult":
        return await self.call("assistant.cancel", params)  # type: ignore[arg-type, return-value]

    async def assistant_confirm(self, params: "t.AssistantConfirmParams") -> "t.AssistantConfirmResult":
        return await self.call("assistant.confirm", params)  # type: ignore[arg-type, return-value]

    async def assistant_consent(self, params: "Optional[t.AssistantConsentParams]" = None) -> "t.AssistantConsentResult":
        return await self.call("assistant.consent", params or {})  # type: ignore[arg-type, return-value]

    async def assistant_generate(self, params: "t.AssistantGenerateParams") -> "t.AssistantGenerateResult":
        return await self.call("assistant.generate", params)  # type: ignore[arg-type, return-value]

    async def assistant_get(self, params: "t.AssistantGetParams") -> "t.AssistantGetResult":
        return await self.call("assistant.get", params)  # type: ignore[arg-type, return-value]

    async def assistant_list(self, params: "Optional[t.AssistantListParams]" = None) -> "t.AssistantListResult":
        return await self.call("assistant.list", params or {})  # type: ignore[arg-type, return-value]

    async def assistant_providers(self, params: "Optional[t.AssistantProvidersParams]" = None) -> "t.AssistantProvidersResult":
        return await self.call("assistant.providers", params or {})  # type: ignore[arg-type, return-value]

    async def assistant_purge(self, params: "Optional[t.AssistantPurgeParams]" = None) -> "t.AssistantPurgeResult":
        return await self.call("assistant.purge", params or {})  # type: ignore[arg-type, return-value]

    async def assistant_revoke(self, params: "Optional[t.AssistantRevokeParams]" = None) -> "t.AssistantRevokeResult":
        return await self.call("assistant.revoke", params or {})  # type: ignore[arg-type, return-value]

    async def assistant_status(self, params: "Optional[t.AssistantStatusParams]" = None) -> "t.AssistantStatusResult":
        return await self.call("assistant.status", params or {})  # type: ignore[arg-type, return-value]

    async def attention_list(self, params: "Optional[t.AttentionListParams]" = None) -> "t.AttentionListResult":
        return await self.call("attention.list", params or {})  # type: ignore[arg-type, return-value]

    async def attention_update(self, params: "t.AttentionUpdateParams") -> "t.AttentionUpdateResult":
        return await self.call("attention.update", params)  # type: ignore[arg-type, return-value]

    async def blob_abort(self, params: "t.BlobAbortParams") -> "t.BlobAbortResult":
        return await self.call("blob.abort", params)  # type: ignore[arg-type, return-value]

    async def blob_append(self, params: "t.BlobAppendParams") -> "t.BlobAppendResult":
        return await self.call("blob.append", params)  # type: ignore[arg-type, return-value]

    async def blob_begin(self, params: "t.BlobBeginParams") -> "t.BlobBeginResult":
        return await self.call("blob.begin", params)  # type: ignore[arg-type, return-value]

    async def blob_commit(self, params: "t.BlobCommitParams") -> "t.BlobCommitResult":
        return await self.call("blob.commit", params)  # type: ignore[arg-type, return-value]

    async def blob_put(self, params: "t.BlobPutParams") -> "t.BlobPutResult":
        return await self.call("blob.put", params)  # type: ignore[arg-type, return-value]

    async def browser_attach_screencast(self, params: "Optional[t.BrowserAttachScreencastParams]" = None) -> "t.BrowserAttachScreencastResult":
        return await self.call("browser.attach_screencast", params or {})  # type: ignore[arg-type, return-value]

    async def browser_click(self, params: "Optional[t.BrowserClickParams]" = None) -> "t.BrowserClickResult":
        return await self.call("browser.click", params or {})  # type: ignore[arg-type, return-value]

    async def browser_close(self, params: "Optional[t.BrowserCloseParams]" = None) -> "t.BrowserCloseResult":
        return await self.call("browser.close", params or {})  # type: ignore[arg-type, return-value]

    async def browser_command(self, params: "t.BrowserCommandParams") -> "t.BrowserCommandResult":
        return await self.call("browser.command", params)  # type: ignore[arg-type, return-value]

    async def browser_console(self, params: "t.BrowserConsoleParams") -> "t.BrowserConsoleResult":
        return await self.call("browser.console", params)  # type: ignore[arg-type, return-value]

    async def browser_detach_screencast(self, params: "Optional[t.BrowserDetachScreencastParams]" = None) -> "t.BrowserDetachScreencastResult":
        return await self.call("browser.detach_screencast", params or {})  # type: ignore[arg-type, return-value]

    async def browser_diff(self, params: "t.BrowserDiffParams") -> "t.BrowserDiffResult":
        return await self.call("browser.diff", params)  # type: ignore[arg-type, return-value]

    async def browser_dom(self, params: "Optional[t.BrowserDomParams]" = None) -> "t.BrowserDomResult":
        return await self.call("browser.dom", params or {})  # type: ignore[arg-type, return-value]

    async def browser_eval(self, params: "Optional[t.BrowserEvalParams]" = None) -> "t.BrowserEvalResult":
        return await self.call("browser.eval", params or {})  # type: ignore[arg-type, return-value]

    async def browser_install(self, params: "Optional[t.BrowserInstallParams]" = None) -> "t.BrowserInstallResult":
        return await self.call("browser.install", params or {})  # type: ignore[arg-type, return-value]

    async def browser_list(self, params: "Optional[t.BrowserListParams]" = None) -> "t.BrowserListResult":
        return await self.call("browser.list", params or {})  # type: ignore[arg-type, return-value]

    async def browser_navigate(self, params: "Optional[t.BrowserNavigateParams]" = None) -> "t.BrowserNavigateResult":
        return await self.call("browser.navigate", params or {})  # type: ignore[arg-type, return-value]

    async def browser_network(self, params: "t.BrowserNetworkParams") -> "t.BrowserNetworkResult":
        return await self.call("browser.network", params)  # type: ignore[arg-type, return-value]

    async def browser_open(self, params: "Optional[t.BrowserOpenParams]" = None) -> "t.BrowserOpenResult":
        return await self.call("browser.open", params or {})  # type: ignore[arg-type, return-value]

    async def browser_pane_console(self, params: "Optional[t.BrowserPaneConsoleParams]" = None) -> "t.BrowserPaneConsoleResult":
        return await self.call("browser.pane.console", params or {})  # type: ignore[arg-type, return-value]

    async def browser_pane_console_push(self, params: "t.BrowserPaneConsolePushParams") -> "t.BrowserPaneConsolePushResult":
        return await self.call("browser.pane.console_push", params)  # type: ignore[arg-type, return-value]

    async def browser_pane_create(self, params: "Optional[t.BrowserPaneCreateParams]" = None) -> "t.BrowserPaneCreateResult":
        return await self.call("browser.pane.create", params or {})  # type: ignore[arg-type, return-value]

    async def browser_pane_list(self, params: "Optional[t.BrowserPaneListParams]" = None) -> "t.BrowserPaneListResult":
        return await self.call("browser.pane.list", params or {})  # type: ignore[arg-type, return-value]

    async def browser_pane_status(self, params: "Optional[t.BrowserPaneStatusParams]" = None) -> "t.BrowserPaneStatusResult":
        return await self.call("browser.pane.status", params or {})  # type: ignore[arg-type, return-value]

    async def browser_pane_update(self, params: "t.BrowserPaneUpdateParams") -> "t.BrowserPaneUpdateResult":
        return await self.call("browser.pane.update", params)  # type: ignore[arg-type, return-value]

    async def browser_press(self, params: "t.BrowserPressParams") -> "t.BrowserPressResult":
        return await self.call("browser.press", params)  # type: ignore[arg-type, return-value]

    async def browser_release(self, params: "Optional[t.BrowserReleaseParams]" = None) -> "t.BrowserReleaseResult":
        return await self.call("browser.release", params or {})  # type: ignore[arg-type, return-value]

    async def browser_screencast_frame(self, params: "Optional[t.BrowserScreencastFrameParams]" = None) -> "t.BrowserScreencastFrameResult":
        return await self.call("browser.screencast_frame", params or {})  # type: ignore[arg-type, return-value]

    async def browser_screenshot(self, params: "Optional[t.BrowserScreenshotParams]" = None) -> "t.BrowserScreenshotResult":
        return await self.call("browser.screenshot", params or {})  # type: ignore[arg-type, return-value]

    async def browser_session_close(self, params: "Optional[t.BrowserSessionCloseParams]" = None) -> "t.BrowserSessionCloseResult":
        return await self.call("browser.session_close", params or {})  # type: ignore[arg-type, return-value]

    async def browser_session_open(self, params: "Optional[t.BrowserSessionOpenParams]" = None) -> "t.BrowserSessionOpenResult":
        return await self.call("browser.session_open", params or {})  # type: ignore[arg-type, return-value]

    async def browser_snapshot(self, params: "Optional[t.BrowserSnapshotParams]" = None) -> "t.BrowserSnapshotResult":
        return await self.call("browser.snapshot", params or {})  # type: ignore[arg-type, return-value]

    async def browser_status(self, params: "Optional[t.BrowserStatusParams]" = None) -> "t.BrowserStatusResult":
        return await self.call("browser.status", params or {})  # type: ignore[arg-type, return-value]

    async def browser_take_over(self, params: "Optional[t.BrowserTakeOverParams]" = None) -> "t.BrowserTakeOverResult":
        return await self.call("browser.take_over", params or {})  # type: ignore[arg-type, return-value]

    async def browser_type(self, params: "t.BrowserTypeParams") -> "t.BrowserTypeResult":
        return await self.call("browser.type", params)  # type: ignore[arg-type, return-value]

    async def browser_wait(self, params: "Optional[t.BrowserWaitParams]" = None) -> "t.BrowserWaitResult":
        return await self.call("browser.wait", params or {})  # type: ignore[arg-type, return-value]

    async def browser_watch(self, params: "Optional[t.BrowserWatchParams]" = None) -> "t.BrowserWatchResult":
        return await self.call("browser.watch", params or {})  # type: ignore[arg-type, return-value]

    async def client_appearance(self, params: "t.ClientAppearanceParams") -> "t.ClientAppearanceResult":
        return await self.call("client.appearance", params)  # type: ignore[arg-type, return-value]

    async def client_focus(self, params: "Optional[t.ClientFocusParams]" = None) -> "t.ClientFocusResult":
        return await self.call("client.focus", params or {})  # type: ignore[arg-type, return-value]

    async def client_hello(self, params: "t.ClientHelloParams") -> "t.ClientHelloResult":
        return await self.call("client.hello", params)  # type: ignore[arg-type, return-value]

    async def client_list(self, params: "Optional[t.ClientListParams]" = None) -> "t.ClientListResult":
        return await self.call("client.list", params or {})  # type: ignore[arg-type, return-value]

    async def compat_herdr_call(self, params: "t.CompatHerdrCallParams") -> "t.CompatHerdrCallResult":
        return await self.call("compat.herdr.call", params)  # type: ignore[arg-type, return-value]

    async def compat_invocation_verify(self, params: "t.CompatInvocationVerifyParams") -> "t.CompatInvocationVerifyResult":
        return await self.call("compat.invocation.verify", params)  # type: ignore[arg-type, return-value]

    async def compat_status(self, params: "Optional[t.CompatStatusParams]" = None) -> "t.CompatStatusResult":
        return await self.call("compat.status", params or {})  # type: ignore[arg-type, return-value]

    async def compat_ui_state(self, params: "Optional[t.CompatUiStateParams]" = None) -> "t.CompatUiStateResult":
        return await self.call("compat.ui.state", params or {})  # type: ignore[arg-type, return-value]

    async def desk_context(self, params: "t.DeskContextParams") -> "t.DeskContextResult":
        return await self.call("desk.context", params)  # type: ignore[arg-type, return-value]

    async def desk_forget(self, params: "Optional[t.DeskForgetParams]" = None) -> "t.DeskForgetResult":
        return await self.call("desk.forget", params or {})  # type: ignore[arg-type, return-value]

    async def desk_index(self, params: "Optional[t.DeskIndexParams]" = None) -> "t.DeskIndexResult":
        return await self.call("desk.index", params or {})  # type: ignore[arg-type, return-value]

    async def desk_open(self, params: "t.DeskOpenParams") -> "t.DeskOpenResult":
        return await self.call("desk.open", params)  # type: ignore[arg-type, return-value]

    async def desk_resume(self, params: "t.DeskResumeParams") -> "t.DeskResumeResult":
        return await self.call("desk.resume", params)  # type: ignore[arg-type, return-value]

    async def desk_search(self, params: "t.DeskSearchParams") -> "t.DeskSearchResult":
        return await self.call("desk.search", params)  # type: ignore[arg-type, return-value]

    async def desk_sessions(self, params: "Optional[t.DeskSessionsParams]" = None) -> "t.DeskSessionsResult":
        return await self.call("desk.sessions", params or {})  # type: ignore[arg-type, return-value]

    async def desk_status(self, params: "Optional[t.DeskStatusParams]" = None) -> "t.DeskStatusResult":
        return await self.call("desk.status", params or {})  # type: ignore[arg-type, return-value]

    async def draft_check(self, params: "t.DraftCheckParams") -> "t.DraftCheckResult":
        return await self.call("draft.check", params)  # type: ignore[arg-type, return-value]

    async def draft_combine(self, params: "t.DraftCombineParams") -> "t.DraftCombineResult":
        return await self.call("draft.combine", params)  # type: ignore[arg-type, return-value]

    async def draft_create(self, params: "t.DraftCreateParams") -> "t.DraftCreateResult":
        return await self.call("draft.create", params)  # type: ignore[arg-type, return-value]

    async def draft_delete(self, params: "t.DraftDeleteParams") -> "t.DraftDeleteResult":
        return await self.call("draft.delete", params)  # type: ignore[arg-type, return-value]

    async def draft_get(self, params: "t.DraftGetParams") -> "t.DraftGetResult":
        return await self.call("draft.get", params)  # type: ignore[arg-type, return-value]

    async def draft_list(self, params: "Optional[t.DraftListParams]" = None) -> "t.DraftListResult":
        return await self.call("draft.list", params or {})  # type: ignore[arg-type, return-value]

    async def draft_reconcile(self, params: "t.DraftReconcileParams") -> "t.DraftReconcileResult":
        return await self.call("draft.reconcile", params)  # type: ignore[arg-type, return-value]

    async def draft_reorder(self, params: "t.DraftReorderParams") -> "t.DraftReorderResult":
        return await self.call("draft.reorder", params)  # type: ignore[arg-type, return-value]

    async def draft_send(self, params: "t.DraftSendParams") -> "t.DraftSendResult":
        return await self.call("draft.send", params)  # type: ignore[arg-type, return-value]

    async def draft_update(self, params: "t.DraftUpdateParams") -> "t.DraftUpdateResult":
        return await self.call("draft.update", params)  # type: ignore[arg-type, return-value]

    async def events_read(self, params: "Optional[t.EventsReadParams]" = None) -> "t.EventsReadResult":
        return await self.call("events.read", params or {})  # type: ignore[arg-type, return-value]

    async def events_subscribe(self, params: "Optional[t.EventsSubscribeParams]" = None) -> "t.EventsSubscribeResult":
        return await self.call("events.subscribe", params or {})  # type: ignore[arg-type, return-value]

    async def events_unsubscribe(self, params: "t.EventsUnsubscribeParams") -> "t.EventsUnsubscribeResult":
        return await self.call("events.unsubscribe", params)  # type: ignore[arg-type, return-value]

    async def events_wait(self, params: "Optional[t.EventsWaitParams]" = None) -> "t.EventsWaitResult":
        return await self.call("events.wait", params or {})  # type: ignore[arg-type, return-value]

    async def fs_list(self, params: "Optional[t.FsListParams]" = None) -> "t.FsListResult":
        return await self.call("fs.list", params or {})  # type: ignore[arg-type, return-value]

    async def fs_read(self, params: "t.FsReadParams") -> "t.FsReadResult":
        return await self.call("fs.read", params)  # type: ignore[arg-type, return-value]

    async def git_diff(self, params: "t.GitDiffParams") -> "t.GitDiffResult":
        return await self.call("git.diff", params)  # type: ignore[arg-type, return-value]

    async def git_log(self, params: "Optional[t.GitLogParams]" = None) -> "t.GitLogResult":
        return await self.call("git.log", params or {})  # type: ignore[arg-type, return-value]

    async def git_status(self, params: "Optional[t.GitStatusParams]" = None) -> "t.GitStatusResult":
        return await self.call("git.status", params or {})  # type: ignore[arg-type, return-value]

    async def group_add(self, params: "t.GroupAddParams") -> "t.GroupAddResult":
        return await self.call("group.add", params)  # type: ignore[arg-type, return-value]

    async def group_collapse(self, params: "t.GroupCollapseParams") -> "t.GroupCollapseResult":
        return await self.call("group.collapse", params)  # type: ignore[arg-type, return-value]

    async def group_create(self, params: "t.GroupCreateParams") -> "t.GroupCreateResult":
        return await self.call("group.create", params)  # type: ignore[arg-type, return-value]

    async def group_delete(self, params: "t.GroupDeleteParams") -> "t.GroupDeleteResult":
        return await self.call("group.delete", params)  # type: ignore[arg-type, return-value]

    async def group_list(self, params: "Optional[t.GroupListParams]" = None) -> "t.GroupListResult":
        return await self.call("group.list", params or {})  # type: ignore[arg-type, return-value]

    async def group_move(self, params: "t.GroupMoveParams") -> "t.GroupMoveResult":
        return await self.call("group.move", params)  # type: ignore[arg-type, return-value]

    async def group_remove(self, params: "Optional[t.GroupRemoveParams]" = None) -> "t.GroupRemoveResult":
        return await self.call("group.remove", params or {})  # type: ignore[arg-type, return-value]

    async def group_rename(self, params: "t.GroupRenameParams") -> "t.GroupRenameResult":
        return await self.call("group.rename", params)  # type: ignore[arg-type, return-value]

    async def image_upload(self, params: "t.ImageUploadParams") -> "t.ImageUploadResult":
        return await self.call("image.upload", params)  # type: ignore[arg-type, return-value]

    async def interaction_answer(self, params: "t.InteractionAnswerParams") -> "t.InteractionAnswerResult":
        return await self.call("interaction.answer", params)  # type: ignore[arg-type, return-value]

    async def interaction_cancel(self, params: "t.InteractionCancelParams") -> "t.InteractionCancelResult":
        return await self.call("interaction.cancel", params)  # type: ignore[arg-type, return-value]

    async def interaction_get(self, params: "t.InteractionGetParams") -> "t.InteractionGetResult":
        return await self.call("interaction.get", params)  # type: ignore[arg-type, return-value]

    async def interaction_list(self, params: "Optional[t.InteractionListParams]" = None) -> "t.InteractionListResult":
        return await self.call("interaction.list", params or {})  # type: ignore[arg-type, return-value]

    async def layout_apply(self, params: "t.LayoutApplyParams") -> "t.LayoutApplyResult":
        return await self.call("layout.apply", params)  # type: ignore[arg-type, return-value]

    async def layout_export(self, params: "Optional[t.LayoutExportParams]" = None) -> "t.LayoutExportResult":
        return await self.call("layout.export", params or {})  # type: ignore[arg-type, return-value]

    async def layout_get(self, params: "Optional[t.LayoutGetParams]" = None) -> "t.LayoutGetResult":
        return await self.call("layout.get", params or {})  # type: ignore[arg-type, return-value]

    async def layout_list(self, params: "Optional[t.LayoutListParams]" = None) -> "t.LayoutListResult":
        return await self.call("layout.list", params or {})  # type: ignore[arg-type, return-value]

    async def notes_get(self, params: "Optional[t.NotesGetParams]" = None) -> "t.NotesGetResult":
        return await self.call("notes.get", params or {})  # type: ignore[arg-type, return-value]

    async def notes_set(self, params: "t.NotesSetParams") -> "t.NotesSetResult":
        return await self.call("notes.set", params)  # type: ignore[arg-type, return-value]

    async def notification_config(self, params: "Optional[t.NotificationConfigParams]" = None) -> "t.NotificationConfigResult":
        return await self.call("notification.config", params or {})  # type: ignore[arg-type, return-value]

    async def notification_list(self, params: "Optional[t.NotificationListParams]" = None) -> "t.NotificationListResult":
        return await self.call("notification.list", params or {})  # type: ignore[arg-type, return-value]

    async def notification_read(self, params: "Optional[t.NotificationReadParams]" = None) -> "t.NotificationReadResult":
        return await self.call("notification.read", params or {})  # type: ignore[arg-type, return-value]

    async def notification_send(self, params: "t.NotificationSendParams") -> "t.NotificationSendResult":
        return await self.call("notification.send", params)  # type: ignore[arg-type, return-value]

    async def pane_can_see_paths(self, params: "Optional[t.PaneCanSeePathsParams]" = None) -> "t.PaneCanSeePathsResult":
        return await self.call("pane.can_see_paths", params or {})  # type: ignore[arg-type, return-value]

    async def pane_close(self, params: "Optional[t.PaneCloseParams]" = None) -> "t.PaneCloseResult":
        return await self.call("pane.close", params or {})  # type: ignore[arg-type, return-value]

    async def pane_current(self, params: "Optional[t.PaneCurrentParams]" = None) -> "t.PaneCurrentResult":
        return await self.call("pane.current", params or {})  # type: ignore[arg-type, return-value]

    async def pane_embed(self, params: "t.PaneEmbedParams") -> "t.PaneEmbedResult":
        return await self.call("pane.embed", params)  # type: ignore[arg-type, return-value]

    async def pane_equalize(self, params: "Optional[t.PaneEqualizeParams]" = None) -> "t.PaneEqualizeResult":
        return await self.call("pane.equalize", params or {})  # type: ignore[arg-type, return-value]

    async def pane_float(self, params: "Optional[t.PaneFloatParams]" = None) -> "t.PaneFloatResult":
        return await self.call("pane.float", params or {})  # type: ignore[arg-type, return-value]

    async def pane_focus(self, params: "t.PaneFocusParams") -> "t.PaneFocusResult":
        return await self.call("pane.focus", params)  # type: ignore[arg-type, return-value]

    async def pane_get(self, params: "Optional[t.PaneGetParams]" = None) -> "t.PaneGetResult":
        return await self.call("pane.get", params or {})  # type: ignore[arg-type, return-value]

    async def pane_list(self, params: "Optional[t.PaneListParams]" = None) -> "t.PaneListResult":
        return await self.call("pane.list", params or {})  # type: ignore[arg-type, return-value]

    async def pane_mark_seen(self, params: "Optional[t.PaneMarkSeenParams]" = None) -> "t.PaneMarkSeenResult":
        return await self.call("pane.mark_seen", params or {})  # type: ignore[arg-type, return-value]

    async def pane_mark_unread(self, params: "Optional[t.PaneMarkUnreadParams]" = None) -> "t.PaneMarkUnreadResult":
        return await self.call("pane.mark_unread", params or {})  # type: ignore[arg-type, return-value]

    async def pane_pin(self, params: "t.PanePinParams") -> "t.PanePinResult":
        return await self.call("pane.pin", params)  # type: ignore[arg-type, return-value]

    async def pane_read(self, params: "Optional[t.PaneReadParams]" = None) -> "t.PaneReadResult":
        return await self.call("pane.read", params or {})  # type: ignore[arg-type, return-value]

    async def pane_rename(self, params: "t.PaneRenameParams") -> "t.PaneRenameResult":
        return await self.call("pane.rename", params)  # type: ignore[arg-type, return-value]

    async def pane_report_agent(self, params: "t.PaneReportAgentParams") -> "t.PaneReportAgentResult":
        return await self.call("pane.report_agent", params)  # type: ignore[arg-type, return-value]

    async def pane_report_agent_session(self, params: "Optional[t.PaneReportAgentSessionParams]" = None) -> "t.PaneReportAgentSessionResult":
        return await self.call("pane.report_agent_session", params or {})  # type: ignore[arg-type, return-value]

    async def pane_resize(self, params: "t.PaneResizeParams") -> "t.PaneResizeResult":
        return await self.call("pane.resize", params)  # type: ignore[arg-type, return-value]

    async def pane_run(self, params: "t.PaneRunParams") -> "t.PaneRunResult":
        return await self.call("pane.run", params)  # type: ignore[arg-type, return-value]

    async def pane_send_bytes(self, params: "t.PaneSendBytesParams") -> "t.PaneSendBytesResult":
        return await self.call("pane.send_bytes", params)  # type: ignore[arg-type, return-value]

    async def pane_send_keys(self, params: "t.PaneSendKeysParams") -> "t.PaneSendKeysResult":
        return await self.call("pane.send_keys", params)  # type: ignore[arg-type, return-value]

    async def pane_send_text(self, params: "t.PaneSendTextParams") -> "t.PaneSendTextResult":
        return await self.call("pane.send_text", params)  # type: ignore[arg-type, return-value]

    async def pane_split(self, params: "Optional[t.PaneSplitParams]" = None) -> "t.PaneSplitResult":
        return await self.call("pane.split", params or {})  # type: ignore[arg-type, return-value]

    async def pane_wait_idle(self, params: "Optional[t.PaneWaitIdleParams]" = None) -> "t.PaneWaitIdleResult":
        return await self.call("pane.wait_idle", params or {})  # type: ignore[arg-type, return-value]

    async def pane_wait_output(self, params: "Optional[t.PaneWaitOutputParams]" = None) -> "t.PaneWaitOutputResult":
        return await self.call("pane.wait_output", params or {})  # type: ignore[arg-type, return-value]

    async def pane_zoom(self, params: "Optional[t.PaneZoomParams]" = None) -> "t.PaneZoomResult":
        return await self.call("pane.zoom", params or {})  # type: ignore[arg-type, return-value]

    async def plugin_action_list(self, params: "Optional[t.PluginActionListParams]" = None) -> "t.PluginActionListResult":
        return await self.call("plugin.action.list", params or {})  # type: ignore[arg-type, return-value]

    async def plugin_action_run(self, params: "t.PluginActionRunParams") -> "t.PluginActionRunResult":
        return await self.call("plugin.action.run", params)  # type: ignore[arg-type, return-value]

    async def plugin_link_open(self, params: "t.PluginLinkOpenParams") -> "t.PluginLinkOpenResult":
        return await self.call("plugin.link.open", params)  # type: ignore[arg-type, return-value]

    async def plugin_link_handler_list(self, params: "Optional[t.PluginLinkHandlerListParams]" = None) -> "t.PluginLinkHandlerListResult":
        return await self.call("plugin.link_handler.list", params or {})  # type: ignore[arg-type, return-value]

    async def plugin_list(self, params: "Optional[t.PluginListParams]" = None) -> "t.PluginListResult":
        return await self.call("plugin.list", params or {})  # type: ignore[arg-type, return-value]

    async def plugin_log_list(self, params: "Optional[t.PluginLogListParams]" = None) -> "t.PluginLogListResult":
        return await self.call("plugin.log.list", params or {})  # type: ignore[arg-type, return-value]

    async def plugin_registry_notify(self, params: "Optional[t.PluginRegistryNotifyParams]" = None) -> "t.PluginRegistryNotifyResult":
        return await self.call("plugin.registry.notify", params or {})  # type: ignore[arg-type, return-value]

    async def plugin_surface_close(self, params: "t.PluginSurfaceCloseParams") -> "t.PluginSurfaceCloseResult":
        return await self.call("plugin.surface.close", params)  # type: ignore[arg-type, return-value]

    async def preview_declare(self, params: "t.PreviewDeclareParams") -> "t.PreviewDeclareResult":
        return await self.call("preview.declare", params)  # type: ignore[arg-type, return-value]

    async def preview_dismiss(self, params: "t.PreviewDismissParams") -> "t.PreviewDismissResult":
        return await self.call("preview.dismiss", params)  # type: ignore[arg-type, return-value]

    async def preview_forget(self, params: "t.PreviewForgetParams") -> "t.PreviewForgetResult":
        return await self.call("preview.forget", params)  # type: ignore[arg-type, return-value]

    async def preview_get(self, params: "t.PreviewGetParams") -> "t.PreviewGetResult":
        return await self.call("preview.get", params)  # type: ignore[arg-type, return-value]

    async def preview_list(self, params: "Optional[t.PreviewListParams]" = None) -> "t.PreviewListResult":
        return await self.call("preview.list", params or {})  # type: ignore[arg-type, return-value]

    async def preview_mirror(self, params: "t.PreviewMirrorParams") -> "t.PreviewMirrorResult":
        return await self.call("preview.mirror", params)  # type: ignore[arg-type, return-value]

    async def preview_open(self, params: "Optional[t.PreviewOpenParams]" = None) -> "t.PreviewOpenResult":
        return await self.call("preview.open", params or {})  # type: ignore[arg-type, return-value]

    async def preview_profile(self, params: "Optional[t.PreviewProfileParams]" = None) -> "t.PreviewProfileResult":
        return await self.call("preview.profile", params or {})  # type: ignore[arg-type, return-value]

    async def preview_profile_list(self, params: "Optional[t.PreviewProfileListParams]" = None) -> "t.PreviewProfileListResult":
        return await self.call("preview.profile.list", params or {})  # type: ignore[arg-type, return-value]

    async def preview_profile_reset(self, params: "Optional[t.PreviewProfileResetParams]" = None) -> "t.PreviewProfileResetResult":
        return await self.call("preview.profile.reset", params or {})  # type: ignore[arg-type, return-value]

    async def preview_promote(self, params: "t.PreviewPromoteParams") -> "t.PreviewPromoteResult":
        return await self.call("preview.promote", params)  # type: ignore[arg-type, return-value]

    async def preview_status(self, params: "Optional[t.PreviewStatusParams]" = None) -> "t.PreviewStatusResult":
        return await self.call("preview.status", params or {})  # type: ignore[arg-type, return-value]

    async def preview_unmirror(self, params: "Optional[t.PreviewUnmirrorParams]" = None) -> "t.PreviewUnmirrorResult":
        return await self.call("preview.unmirror", params or {})  # type: ignore[arg-type, return-value]

    async def preview_url(self, params: "t.PreviewUrlParams") -> "t.PreviewUrlResult":
        return await self.call("preview.url", params)  # type: ignore[arg-type, return-value]

    async def sandbox_allow(self, params: "t.SandboxAllowParams") -> "t.SandboxAllowResult":
        return await self.call("sandbox.allow", params)  # type: ignore[arg-type, return-value]

    async def sandbox_list(self, params: "Optional[t.SandboxListParams]" = None) -> "t.SandboxListResult":
        return await self.call("sandbox.list", params or {})  # type: ignore[arg-type, return-value]

    async def sandbox_remove(self, params: "t.SandboxRemoveParams") -> "t.SandboxRemoveResult":
        return await self.call("sandbox.remove", params)  # type: ignore[arg-type, return-value]

    async def sandbox_start(self, params: "t.SandboxStartParams") -> "t.SandboxStartResult":
        return await self.call("sandbox.start", params)  # type: ignore[arg-type, return-value]

    async def sandbox_status(self, params: "Optional[t.SandboxStatusParams]" = None) -> "t.SandboxStatusResult":
        return await self.call("sandbox.status", params or {})  # type: ignore[arg-type, return-value]

    async def sandbox_stop(self, params: "t.SandboxStopParams") -> "t.SandboxStopResult":
        return await self.call("sandbox.stop", params)  # type: ignore[arg-type, return-value]

    async def screenshot_delete(self, params: "t.ScreenshotDeleteParams") -> "t.ScreenshotDeleteResult":
        return await self.call("screenshot.delete", params)  # type: ignore[arg-type, return-value]

    async def screenshot_get(self, params: "t.ScreenshotGetParams") -> "t.ScreenshotGetResult":
        return await self.call("screenshot.get", params)  # type: ignore[arg-type, return-value]

    async def screenshot_list(self, params: "Optional[t.ScreenshotListParams]" = None) -> "t.ScreenshotListResult":
        return await self.call("screenshot.list", params or {})  # type: ignore[arg-type, return-value]

    async def screenshot_open(self, params: "t.ScreenshotOpenParams") -> "t.ScreenshotOpenResult":
        return await self.call("screenshot.open", params)  # type: ignore[arg-type, return-value]

    async def scrollback_forget(self, params: "Optional[t.ScrollbackForgetParams]" = None) -> "t.ScrollbackForgetResult":
        return await self.call("scrollback.forget", params or {})  # type: ignore[arg-type, return-value]

    async def search_query(self, params: "t.SearchQueryParams") -> "t.SearchQueryResult":
        return await self.call("search.query", params)  # type: ignore[arg-type, return-value]

    async def server_reload_config(self, params: "Optional[t.ServerReloadConfigParams]" = None) -> "t.ServerReloadConfigResult":
        return await self.call("server.reload_config", params or {})  # type: ignore[arg-type, return-value]

    async def server_status(self, params: "Optional[t.ServerStatusParams]" = None) -> "t.ServerStatusResult":
        return await self.call("server.status", params or {})  # type: ignore[arg-type, return-value]

    async def server_stop(self, params: "Optional[t.ServerStopParams]" = None) -> "t.ServerStopResult":
        return await self.call("server.stop", params or {})  # type: ignore[arg-type, return-value]

    async def session_snapshot(self, params: "Optional[t.SessionSnapshotParams]" = None) -> "t.SessionSnapshotResult":
        return await self.call("session.snapshot", params or {})  # type: ignore[arg-type, return-value]

    async def status_segments(self, params: "Optional[t.StatusSegmentsParams]" = None) -> "t.StatusSegmentsResult":
        return await self.call("status.segments", params or {})  # type: ignore[arg-type, return-value]

    async def tab_close(self, params: "t.TabCloseParams") -> "t.TabCloseResult":
        return await self.call("tab.close", params)  # type: ignore[arg-type, return-value]

    async def tab_create(self, params: "Optional[t.TabCreateParams]" = None) -> "t.TabCreateResult":
        return await self.call("tab.create", params or {})  # type: ignore[arg-type, return-value]

    async def tab_floats(self, params: "Optional[t.TabFloatsParams]" = None) -> "t.TabFloatsResult":
        return await self.call("tab.floats", params or {})  # type: ignore[arg-type, return-value]

    async def tab_focus(self, params: "t.TabFocusParams") -> "t.TabFocusResult":
        return await self.call("tab.focus", params)  # type: ignore[arg-type, return-value]

    async def tab_list(self, params: "Optional[t.TabListParams]" = None) -> "t.TabListResult":
        return await self.call("tab.list", params or {})  # type: ignore[arg-type, return-value]

    async def tab_move(self, params: "t.TabMoveParams") -> "t.TabMoveResult":
        return await self.call("tab.move", params)  # type: ignore[arg-type, return-value]

    async def tab_rename(self, params: "t.TabRenameParams") -> "t.TabRenameResult":
        return await self.call("tab.rename", params)  # type: ignore[arg-type, return-value]

    async def task_check_authorize(self, params: "t.TaskCheckAuthorizeParams") -> "t.TaskCheckAuthorizeResult":
        return await self.call("task.check.authorize", params)  # type: ignore[arg-type, return-value]

    async def task_check_cancel(self, params: "t.TaskCheckCancelParams") -> "t.TaskCheckCancelResult":
        return await self.call("task.check.cancel", params)  # type: ignore[arg-type, return-value]

    async def task_check_get(self, params: "t.TaskCheckGetParams") -> "t.TaskCheckGetResult":
        return await self.call("task.check.get", params)  # type: ignore[arg-type, return-value]

    async def task_check_list(self, params: "t.TaskCheckListParams") -> "t.TaskCheckListResult":
        return await self.call("task.check.list", params)  # type: ignore[arg-type, return-value]

    async def task_check_run(self, params: "t.TaskCheckRunParams") -> "t.TaskCheckRunResult":
        return await self.call("task.check.run", params)  # type: ignore[arg-type, return-value]

    async def task_create(self, params: "t.TaskCreateParams") -> "t.TaskCreateResult":
        return await self.call("task.create", params)  # type: ignore[arg-type, return-value]

    async def task_dependency_add(self, params: "t.TaskDependencyAddParams") -> "t.TaskDependencyAddResult":
        return await self.call("task.dependency.add", params)  # type: ignore[arg-type, return-value]

    async def task_dependency_list(self, params: "Optional[t.TaskDependencyListParams]" = None) -> "t.TaskDependencyListResult":
        return await self.call("task.dependency.list", params or {})  # type: ignore[arg-type, return-value]

    async def task_dependency_remove(self, params: "t.TaskDependencyRemoveParams") -> "t.TaskDependencyRemoveResult":
        return await self.call("task.dependency.remove", params)  # type: ignore[arg-type, return-value]

    async def task_effort_estimate(self, params: "t.TaskEffortEstimateParams") -> "t.TaskEffortEstimateResult":
        return await self.call("task.effort.estimate", params)  # type: ignore[arg-type, return-value]

    async def task_finish(self, params: "t.TaskFinishParams") -> "t.TaskFinishResult":
        return await self.call("task.finish", params)  # type: ignore[arg-type, return-value]

    async def task_get(self, params: "t.TaskGetParams") -> "t.TaskGetResult":
        return await self.call("task.get", params)  # type: ignore[arg-type, return-value]

    async def task_list(self, params: "Optional[t.TaskListParams]" = None) -> "t.TaskListResult":
        return await self.call("task.list", params or {})  # type: ignore[arg-type, return-value]

    async def task_review_accept(self, params: "t.TaskReviewAcceptParams") -> "t.TaskReviewAcceptResult":
        return await self.call("task.review.accept", params)  # type: ignore[arg-type, return-value]

    async def task_review_candidates(self, params: "t.TaskReviewCandidatesParams") -> "t.TaskReviewCandidatesResult":
        return await self.call("task.review.candidates", params)  # type: ignore[arg-type, return-value]

    async def task_review_diff(self, params: "t.TaskReviewDiffParams") -> "t.TaskReviewDiffResult":
        return await self.call("task.review.diff", params)  # type: ignore[arg-type, return-value]

    async def task_review_get(self, params: "t.TaskReviewGetParams") -> "t.TaskReviewGetResult":
        return await self.call("task.review.get", params)  # type: ignore[arg-type, return-value]

    async def task_review_note_classify(self, params: "t.TaskReviewNoteClassifyParams") -> "t.TaskReviewNoteClassifyResult":
        return await self.call("task.review.note.classify", params)  # type: ignore[arg-type, return-value]

    async def task_review_notes(self, params: "t.TaskReviewNotesParams") -> "t.TaskReviewNotesResult":
        return await self.call("task.review.notes", params)  # type: ignore[arg-type, return-value]

    async def task_review_request_reviewer(self, params: "t.TaskReviewRequestReviewerParams") -> "t.TaskReviewRequestReviewerResult":
        return await self.call("task.review.request_reviewer", params)  # type: ignore[arg-type, return-value]

    async def task_review_snapshot(self, params: "t.TaskReviewSnapshotParams") -> "t.TaskReviewSnapshotResult":
        return await self.call("task.review.snapshot", params)  # type: ignore[arg-type, return-value]

    async def task_review_snapshot_gc(self, params: "t.TaskReviewSnapshotGcParams") -> "t.TaskReviewSnapshotGcResult":
        return await self.call("task.review.snapshot.gc", params)  # type: ignore[arg-type, return-value]

    async def task_review_start_reviewer(self, params: "t.TaskReviewStartReviewerParams") -> "t.TaskReviewStartReviewerResult":
        return await self.call("task.review.start_reviewer", params)  # type: ignore[arg-type, return-value]

    async def task_sync(self, params: "t.TaskSyncParams") -> "t.TaskSyncResult":
        return await self.call("task.sync", params)  # type: ignore[arg-type, return-value]

    async def theme_get(self, params: "Optional[t.ThemeGetParams]" = None) -> "t.ThemeGetResult":
        return await self.call("theme.get", params or {})  # type: ignore[arg-type, return-value]

    async def theme_set_mode(self, params: "t.ThemeSetModeParams") -> "t.ThemeSetModeResult":
        return await self.call("theme.set_mode", params)  # type: ignore[arg-type, return-value]

    async def workspace_close(self, params: "Optional[t.WorkspaceCloseParams]" = None) -> "t.WorkspaceCloseResult":
        return await self.call("workspace.close", params or {})  # type: ignore[arg-type, return-value]

    async def workspace_create(self, params: "Optional[t.WorkspaceCreateParams]" = None) -> "t.WorkspaceCreateResult":
        return await self.call("workspace.create", params or {})  # type: ignore[arg-type, return-value]

    async def workspace_focus(self, params: "t.WorkspaceFocusParams") -> "t.WorkspaceFocusResult":
        return await self.call("workspace.focus", params)  # type: ignore[arg-type, return-value]

    async def workspace_get(self, params: "Optional[t.WorkspaceGetParams]" = None) -> "t.WorkspaceGetResult":
        return await self.call("workspace.get", params or {})  # type: ignore[arg-type, return-value]

    async def workspace_list(self, params: "Optional[t.WorkspaceListParams]" = None) -> "t.WorkspaceListResult":
        return await self.call("workspace.list", params or {})  # type: ignore[arg-type, return-value]

    async def workspace_move(self, params: "t.WorkspaceMoveParams") -> "t.WorkspaceMoveResult":
        return await self.call("workspace.move", params)  # type: ignore[arg-type, return-value]

    async def workspace_rename(self, params: "t.WorkspaceRenameParams") -> "t.WorkspaceRenameResult":
        return await self.call("workspace.rename", params)  # type: ignore[arg-type, return-value]

    async def worktree_create(self, params: "t.WorktreeCreateParams") -> "t.WorktreeCreateResult":
        return await self.call("worktree.create", params)  # type: ignore[arg-type, return-value]

    async def worktree_list(self, params: "Optional[t.WorktreeListParams]" = None) -> "t.WorktreeListResult":
        return await self.call("worktree.list", params or {})  # type: ignore[arg-type, return-value]

    async def worktree_open(self, params: "t.WorktreeOpenParams") -> "t.WorktreeOpenResult":
        return await self.call("worktree.open", params)  # type: ignore[arg-type, return-value]

    async def worktree_remove(self, params: "t.WorktreeRemoveParams") -> "t.WorktreeRemoveResult":
        return await self.call("worktree.remove", params)  # type: ignore[arg-type, return-value]

    async def worktree_repo_root(self, params: "t.WorktreeRepoRootParams") -> "t.WorktreeRepoRootResult":
        return await self.call("worktree.repo_root", params)  # type: ignore[arg-type, return-value]

