"""Hand-written runtime of the Vibeke control-API client (spec 07 §1). Standard library only.

Types and typed method wrappers come from ``types_gen.py`` / ``api_gen.py``, generated by
``VIBEKE_UPDATE_CLIENTS=1 cargo test -p vibeke --test api_clients``.

Transport: JSON-RPC 2.0, one JSON object per line on the session's unix socket. Lines are split
on ``\\n`` only (U+2028/U+2029 are legal inside JSON strings, so ``str.splitlines`` is wrong).
The connection is long-lived and multiplexed: requests are pipelined and correlated by id and
event subscriptions share it.
"""

from __future__ import annotations

import asyncio
import json
import os
import tempfile
from dataclasses import dataclass, field
from typing import Any, AsyncIterator, Dict, List, Optional, Union

from .api_gen import Api
from .types_gen import API_VERSION

MAX_LINE_BYTES = 16 * 1024 * 1024


class VibekeError(Exception):
    """An error response; ``kind`` is the stable machine-readable string (07 §1.4)."""

    def __init__(self, error: Dict[str, Any]):
        data = error.get("data") or {}
        self.code: int = error.get("code", -32050)
        self.kind: str = data.get("kind", "internal")
        self.details: Any = data.get("details")
        self.retryable: bool = bool(data.get("retryable", False))
        self.message: str = error.get("message", "")
        super().__init__(f"{self.kind}: {self.message}")


class EventOverflow(Exception):
    """The subscription's server-side queue overflowed: resubscribe with ``after=resume_from``."""

    def __init__(self, resume_from: Dict[str, Any]):
        self.resume_from = resume_from
        super().__init__("events.overflow: resubscribe from the resume cursor")


@dataclass
class Event:
    """An event from the log (07 §2.13). ``type`` may be one this client does not know."""

    seq: int
    ts: int
    v: int
    tier: str
    type: str
    subject: Dict[str, Any] = field(default_factory=dict)
    actor: Dict[str, Any] = field(default_factory=dict)
    data: Any = None

    @staticmethod
    def from_json(e: Dict[str, Any]) -> "Event":
        return Event(
            seq=e["seq"],
            ts=e.get("ts", 0),
            v=e.get("v", 1),
            tier=e.get("tier", "sync"),
            type=e["type"],
            subject=e.get("subject") or {},
            actor=e.get("actor") or {},
            data=e.get("data"),
        )


def default_socket_path(session: Optional[str] = None) -> str:
    """``$VIBEKE_SOCKET``, else ``<runtime root>/<session>/vibeke.sock``."""
    session = session or os.environ.get("VIBEKE_SESSION") or "default"
    explicit = os.environ.get("VIBEKE_SOCKET")
    if explicit and (os.environ.get("VIBEKE_SESSION") or "default") == session:
        return explicit
    if os.environ.get("VIBEKE_RUNTIME_DIR"):
        root = os.environ["VIBEKE_RUNTIME_DIR"]
    elif os.environ.get("XDG_RUNTIME_DIR"):
        root = os.path.join(os.environ["XDG_RUNTIME_DIR"], "vibeke")
    else:
        tmp = os.environ.get("TMPDIR") or tempfile.gettempdir() or "/tmp"
        root = os.path.join(tmp, f"vibeke-{os.getuid()}")
    return os.path.join(root, session, "vibeke.sock")


_END = object()


class EventStream:
    """An async iterator of :class:`Event`; ``async for ev in stream``. Ends when closed or the
    connection drops; raises :class:`EventOverflow` if the server overflowed it."""

    def __init__(self, subscription_id: str, at: Dict[str, Any], client: "Client"):
        self.subscription_id = subscription_id
        self.at = at
        self._client = client
        self._queue: "asyncio.Queue[Any]" = asyncio.Queue()
        self._closed = False

    def _push(self, e: Event) -> None:
        if not self._closed:
            self._queue.put_nowait(e)

    def _end(self, error: Optional[BaseException] = None) -> None:
        if not self._closed:
            self._closed = True
            self._queue.put_nowait(error if error is not None else _END)

    async def close(self) -> None:
        self._client._streams.pop(self.subscription_id, None)
        self._end()

    def __aiter__(self) -> "EventStream":
        return self

    async def __anext__(self) -> Event:
        item = await self._queue.get()
        if item is _END:
            self._queue.put_nowait(_END)
            raise StopAsyncIteration
        if isinstance(item, BaseException):
            self._queue.put_nowait(_END)
            raise item
        return item

    async def next(self, timeout: Optional[float] = None) -> Event:
        """The next event, or ``asyncio.TimeoutError``."""
        return await asyncio.wait_for(self.__anext__(), timeout)


class Client(Api):
    """Connection to a Vibeke server. Use ``await Client.connect()``; every API method is also a
    typed coroutine (``await c.workspace_list({})``, from ``api_gen.Api``)."""

    def __init__(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
        self._reader = reader
        self._writer = writer
        self._next_id = 1
        self._pending: Dict[int, "asyncio.Future[Any]"] = {}
        self._streams: Dict[str, EventStream] = {}
        self._early: Dict[str, List[Event]] = {}
        self._closed: Optional[BaseException] = None
        self._task: Optional["asyncio.Task[None]"] = None
        self.hello: Optional[Dict[str, Any]] = None

    @classmethod
    async def connect(
        cls,
        socket_path: Optional[str] = None,
        *,
        session: Optional[str] = None,
        token: Optional[str] = None,
        client: str = "vibeke-client-py",
        kind: str = "plugin",
        hello: bool = True,
    ) -> "Client":
        path = socket_path or default_socket_path(session)
        reader, writer = await asyncio.open_unix_connection(path, limit=MAX_LINE_BYTES)
        c = cls(reader, writer)
        c._task = asyncio.get_running_loop().create_task(c._read_loop())
        if hello:
            tok = token if token is not None else os.environ.get("VIBEKE_PANE_TOKEN", "")
            c.hello = await c.call(
                "client.hello",
                {"client": client, "version": "0.1.0", "api": API_VERSION, "kind": kind, "token": tok},
            )
        return c

    async def __aenter__(self) -> "Client":
        return self

    async def __aexit__(self, *exc: Any) -> None:
        await self.close()

    async def call(
        self, method: str, params: Optional[Dict[str, Any]] = None, *, timeout: Optional[float] = None
    ) -> Any:
        """Call a method; returns the result or raises :class:`VibekeError`."""
        if self._closed is not None:
            raise self._closed
        rid = self._next_id
        self._next_id += 1
        fut: "asyncio.Future[Any]" = asyncio.get_running_loop().create_future()
        self._pending[rid] = fut
        line = json.dumps({"jsonrpc": "2.0", "id": rid, "method": method, "params": params or {}})
        self._writer.write(line.encode("utf-8") + b"\n")
        try:
            await self._writer.drain()
            return await asyncio.wait_for(fut, timeout) if timeout else await fut
        finally:
            self._pending.pop(rid, None)

    async def events(
        self,
        types: Optional[List[str]] = None,
        after: Union[Dict[str, Any], int, None] = None,
        subjects: Optional[Dict[str, str]] = None,
    ) -> EventStream:
        """Subscribe (``events.subscribe``); iterate the returned stream with ``async for``."""
        params: Dict[str, Any] = {}
        if types:
            params["types"] = types
        if after is not None:
            params["after"] = after
        if subjects:
            params["subjects"] = subjects
        r = await self.call("events.subscribe", params)
        stream = EventStream(r["subscription_id"], r["at"], self)
        self._streams[stream.subscription_id] = stream
        for e in self._early.pop(stream.subscription_id, []):
            stream._push(e)
        if self._closed is not None:
            stream._end()
        return stream

    async def close(self) -> None:
        self._fail(ConnectionError("connection closed"))
        self._writer.close()
        try:
            await self._writer.wait_closed()
        except Exception:
            pass
        if self._task:
            self._task.cancel()
            try:
                await self._task
            except (asyncio.CancelledError, Exception):
                pass

    async def _read_loop(self) -> None:
        try:
            while True:
                try:
                    raw = await self._reader.readuntil(b"\n")
                except asyncio.IncompleteReadError:
                    break
                except asyncio.LimitOverrunError:
                    raise ConnectionError("line exceeds 16 MiB")
                line = raw[:-1].decode("utf-8")
                if line.strip():
                    self._on_message(line)
        except Exception as e:  # noqa: BLE001 - surfaced to every waiter
            self._fail(e)
            return
        self._fail(ConnectionError("connection closed"))

    def _on_message(self, line: str) -> None:
        try:
            m = json.loads(line)
        except ValueError:
            return
        if m.get("id") is not None and ("result" in m or "error" in m):
            fut = self._pending.get(m["id"])
            if fut is None or fut.done():
                return
            if m.get("error"):
                fut.set_exception(VibekeError(m["error"]))
            else:
                fut.set_result(m.get("result"))
            return
        method = m.get("method")
        params = m.get("params") or {}
        if method == "events.event":
            sid = params["subscription_id"]
            ev = Event.from_json(params["event"])
            stream = self._streams.get(sid)
            if stream is not None:
                stream._push(ev)
            else:
                self._early.setdefault(sid, []).append(ev)
        elif method == "events.overflow":
            stream = self._streams.pop(params["subscription_id"], None)
            if stream is not None:
                stream._end(EventOverflow(params["resume_from"]))
        # Unknown notifications are ignored (07 §1.5).

    def _fail(self, err: BaseException) -> None:
        if self._closed is not None:
            return
        self._closed = err
        for fut in self._pending.values():
            if not fut.done():
                fut.set_exception(err)
        self._pending.clear()
        for s in list(self._streams.values()):
            s._end()
        self._streams.clear()
