//! macOS Seatbelt backend (13 §2.1 `sandbox`): render a [`Policy`] as an SBPL profile and wrap
//! the child command with `sandbox-exec -f <profile>`.
//!
//! `sandbox-exec` and SBPL are deprecated by Apple (the man page says so since macOS 10.12) but
//! still ship with every macOS release and are what Claude Code and Codex use for their own
//! sandboxes. If Apple removes them, the `container`/`vm` levels remain.
//!
//! Seatbelt evaluates rules in order and the **last** matching rule wins; the profile is laid
//! out in the layer order documented in [`crate::policy`].

use crate::policy::{Policy, regex_escape};
use std::fmt::Write as _;
use std::path::Path;

pub const SANDBOX_EXEC: &str = "/usr/bin/sandbox-exec";

/// The system DNS resolver's socket: the only Unix socket an open-network profile adds.
pub const MDNS_RESPONDER: &str = "/private/var/run/mDNSResponder";

/// `TIOCSTI` on Darwin: `_IOW('t', 114, char)`.
pub const TIOCSTI: u64 = 0x8001_7472;

/// Mach services a contained process tree may look up. Deliberately absent: LaunchServices
/// (`open` would start apps outside the sandbox), the pasteboard, securityd/Keychain, DNS
/// (`com.apple.dnssd.service`; the proxy resolves), and user preferences (`cfprefsd.agent`).
pub const MACH_SERVICES: &[&str] = &[
    "com.apple.system.opendirectoryd.libinfo",
    "com.apple.system.opendirectoryd.membership",
    "com.apple.system.logger",
    "com.apple.logd",
    "com.apple.system.notification_center",
    "com.apple.bsd.dirhelper",
    "com.apple.trustd",
    "com.apple.trustd.agent",
    "com.apple.ocspd",
    "com.apple.FSEvents",
    "com.apple.SystemConfiguration.configd",
    "com.apple.cfprefsd.daemon",
];

/// Quote a string for SBPL.
pub fn q(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn qp(p: &Path) -> String {
    q(&p.to_string_lossy())
}

fn rule(out: &mut String, verb: &str, op: &str, filters: &[String]) {
    if filters.is_empty() {
        return;
    }
    let _ = writeln!(out, "({verb} {op}");
    for f in filters {
        let _ = writeln!(out, "  {f}");
    }
    out.push_str(")\n");
}

fn subpaths(ps: &[std::path::PathBuf]) -> Vec<String> {
    ps.iter().map(|p| format!("(subpath {})", qp(p))).collect()
}

/// Render the SBPL profile.
pub fn render(p: &Policy) -> String {
    let mut o = String::new();
    o.push_str("(version 1)\n");
    o.push_str(
        ";; Generated by Vibeke (spec 13 sandbox level). Do not edit: regenerated per pane.\n",
    );
    o.push_str("(deny default)\n\n");

    o.push_str(";; processes\n");
    o.push_str("(allow process-exec)\n(allow process-fork)\n");
    o.push_str("(allow signal (target same-sandbox))\n");
    o.push_str("(allow process-info* (target same-sandbox))\n");
    o.push_str("(allow sysctl-read)\n");
    o.push_str(
        "(deny sysctl-read (sysctl-name \"kern.procargs\") (sysctl-name \"kern.procargs2\"))\n",
    );
    o.push_str("(allow pseudo-tty)\n");
    o.push_str("(allow file-ioctl (regex #\"^/dev/\"))\n");
    // TIOCSTI pushes bytes into a terminal's *input* queue: a contained process sharing a
    // terminal with an unsandboxed shell (an isolated agent typed into a host pane) could queue
    // a command for that shell. XNU allows it on the caller's controlling tty, so deny it here
    // (verified on macOS 26 by the real `sandbox-exec` test `tiocsti_cannot_inject_into_parent`).
    // Seatbelt matches the low 16 bits of the request in some releases and the full value in
    // others: deny every spelling.
    let _ = writeln!(
        o,
        "(deny file-ioctl (ioctl-command {}) (ioctl-command {}) (ioctl-command {}))",
        TIOCSTI & 0xffff,
        TIOCSTI & !0x1fff_0000,
        TIOCSTI
    );
    o.push_str("(allow ipc-posix-sem)\n(allow ipc-posix-shm)\n");
    o.push_str("(allow system-socket)\n");
    let mach: Vec<String> = MACH_SERVICES
        .iter()
        .map(|s| format!("(global-name {})", q(s)))
        .collect();
    rule(&mut o, "allow", "mach-lookup", &mach);

    o.push_str("\n;; reads: everything outside the deny roots (layer 1) …\n");
    o.push_str("(allow file-read*)\n");
    rule(&mut o, "deny", "file-read*", &subpaths(&p.deny_read));
    o.push_str(";; … the home allowlist, checkout and git dirs (layer 2) …\n");
    rule(&mut o, "allow", "file-read*", &subpaths(&p.allow_read));
    o.push_str(";; … Vibeke's own runtime/state/config and $TMPDIR stay hidden (layer 2b) …\n");
    rule(&mut o, "deny", "file-read*", &subpaths(&p.hidden));
    rule(&mut o, "allow", "file-read*", &subpaths(&p.allow_read_late));
    rule(&mut o, "deny", "file-read*", &subpaths(&p.never_read));
    o.push_str(";; stat/realpath anywhere (names and sizes, never contents)\n");
    o.push_str("(allow file-read-metadata)\n");

    o.push_str("\n;; writes (layer 3)\n");
    let mut w = subpaths(&p.allow_write);
    w.push(
        "(regex #\"^/dev/(null|zero|tty|ttys[0-9]+|ptmx|fd/[0-9]+|stdout|stderr|dtracehelper)$\")"
            .into(),
    );
    rule(&mut o, "allow", "file-write*", &w);
    rule(&mut o, "deny", "file-write*", &subpaths(&p.deny_write_git));
    let mut gw = subpaths(&p.allow_write_git);
    gw.extend(
        p.allow_write_regex
            .iter()
            .map(|r| format!("(regex {})", q(r))),
    );
    rule(&mut o, "allow", "file-write*", &gw);
    o.push_str(
        ";; never writable: git hooks/config, the .git link, the checkout root, credentials\n",
    );
    let mut dw = subpaths(&p.deny_write);
    dw.extend(
        p.deny_write_literal
            .iter()
            .map(|x| format!("(literal {})", qp(x))),
    );
    rule(&mut o, "deny", "file-write*", &dw);

    o.push_str("\n;; network\n");
    let mut net: Vec<String> = Vec::new();
    if let Some((port, locals)) = &p.network {
        net.push(format!("(remote ip \"localhost:{port}\")"));
        for l in locals {
            net.push(format!("(remote ip \"localhost:{l}\")"));
        }
    }
    for s in &p.unix_sockets {
        net.push(format!("(remote unix-socket (path-literal {}))", qp(s)));
    }
    if p.network_open {
        // Open network means remote IP endpoints only: a bare `(allow network-outbound)` would
        // also allow connecting to every Unix socket of the user (other plugins' brokers, agent
        // sockets, Vibeke's own). The one extra socket is the system resolver, without which
        // host names do not resolve on macOS.
        net.push("(remote ip \"*:*\")".into());
        net.push(format!(
            "(remote unix-socket (path-literal {}))",
            q(MDNS_RESPONDER)
        ));
    }
    rule(&mut o, "allow", "network-outbound", &net);
    if p.allow_bind_localhost {
        o.push_str("(allow network-bind (local ip \"localhost:*\"))\n");
        o.push_str("(allow network-inbound (local ip \"localhost:*\"))\n");
    }
    o
}

/// `sandbox-exec -f <profile> <argv…>`.
pub fn wrap_argv(profile: &Path, argv: &[String]) -> Vec<String> {
    let mut v = vec![
        SANDBOX_EXEC.to_string(),
        "-f".to_string(),
        profile.to_string_lossy().into_owned(),
    ];
    v.extend(argv.iter().cloned());
    v
}

/// Is Seatbelt usable here (`vibeke doctor`, 13 §11)?
pub fn available() -> bool {
    cfg!(target_os = "macos") && Path::new(SANDBOX_EXEC).exists()
}

/// Escape helper re-exported for profile extensions written by callers.
pub fn regex_literal(s: &str) -> String {
    regex_escape(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::tests::spec;

    #[test]
    fn profile_shape() {
        let t = tempfile::tempdir().unwrap();
        let root = t.path().canonicalize().unwrap();
        let pol = Policy::from_spec(&spec(&root));
        let sb = render(&pol);
        assert!(sb.starts_with("(version 1)\n"));
        assert!(sb.contains("(deny default)"));
        // Layer order: home deny, then allowlist, then hidden, then late allows.
        let i_deny_home = sb
            .find(&format!("(subpath \"{}\")", root.join("home").display()))
            .unwrap();
        let i_checkout = sb
            .find(&format!(
                "(subpath \"{}\")",
                root.join("home/code/repo-task").display()
            ))
            .unwrap();
        let i_hidden = sb
            .find(&format!("(subpath \"{}\")", root.join("state").display()))
            .unwrap();
        let i_inbox = sb
            .find(&format!(
                "(subpath \"{}\")",
                root.join("state/inbox").display()
            ))
            .unwrap();
        assert!(i_deny_home < i_checkout && i_checkout < i_hidden && i_hidden < i_inbox);
        assert!(sb.contains("(remote ip \"localhost:4100\")"));
        assert!(sb.contains("(remote ip \"localhost:20000\")"));
        assert!(sb.contains("(remote unix-socket (path-literal"));
        assert!(sb.contains("refs/heads/vk/task(\\\\.lock)?$"));
        assert!(!sb.contains("com.apple.coreservices.launchservicesd"));
        assert!(!sb.contains("com.apple.pasteboard"));
        // Terminal input injection is denied after the /dev ioctl allow.
        let i_ioctl = sb.find("(allow file-ioctl").unwrap();
        let i_sti = sb.find("(deny file-ioctl (ioctl-command 29810)").unwrap();
        assert!(i_sti > i_ioctl);
        // Git-executed files inside the checkout are in the final write deny.
        let hooks = format!(
            "(subpath \"{}\")",
            root.join("home/code/repo-task/.githooks").display()
        );
        assert!(sb.rfind(&hooks).unwrap() > sb.rfind("(allow file-write*").unwrap());
        // Final deny block comes after every write allow.
        let last_allow = sb.rfind("(allow file-write*").unwrap();
        let final_deny = sb.rfind("(deny file-write*").unwrap();
        assert!(final_deny > last_allow);
    }

    #[test]
    fn no_network_without_proxy() {
        let t = tempfile::tempdir().unwrap();
        let root = t.path().canonicalize().unwrap();
        let mut s = spec(&root);
        s.network = crate::policy::NetMode::None;
        s.unix_sockets.clear();
        let sb = render(&Policy::from_spec(&s));
        assert!(!sb.contains("network-outbound"));
    }

    #[test]
    fn open_network_keeps_the_unix_socket_allowlist() {
        let t = tempfile::tempdir().unwrap();
        let root = t.path().canonicalize().unwrap();
        let mut s = spec(&root);
        s.network = crate::policy::NetMode::Open;
        let pol = Policy::from_spec(&s);
        let sb = render(&pol);
        assert!(
            !sb.contains("(allow network-outbound)"),
            "never an unfiltered outbound allow\n{sb}"
        );
        let start = sb.find("(allow network-outbound\n").unwrap();
        let block = &sb[start..start + sb[start..].find("\n)\n").unwrap()];
        assert!(block.contains("(remote ip \"*:*\")"), "{block}");
        let unix: Vec<&str> = block
            .lines()
            .filter(|l| l.contains("remote unix-socket"))
            .collect();
        assert_eq!(
            unix.len(),
            pol.unix_sockets.len() + 1,
            "own sockets plus the resolver only: {unix:?}"
        );
        assert!(block.contains(MDNS_RESPONDER));
        for u in &pol.unix_sockets {
            assert!(block.contains(&u.display().to_string()));
        }
    }

    #[test]
    fn quoting() {
        assert_eq!(q(r#"a"b\c"#), r#""a\"b\\c""#);
        assert_eq!(
            wrap_argv(Path::new("/p.sb"), &["sh".into(), "-l".into()]),
            vec![SANDBOX_EXEC, "-f", "/p.sb", "sh", "-l"]
        );
    }
}
