//! Conformance vectors shared with `@vibeke/core` (spec 16 §11).
//!
//! `VK_E2E_WRITE_VECTORS=1 cargo test -p vk-e2e --test vectors` regenerates `tests/vectors.json`;
//! otherwise the test checks that the file still matches what this implementation produces.

use serde_json::{Value, json};
use vk_e2e::{Hello, Initiator, Responder, b64, keys::x25519_public};

fn bytes(seed: u8) -> [u8; 32] {
    std::array::from_fn(|i| seed.wrapping_add(i as u8).wrapping_mul(7))
}

fn case(name: &str, psk: Option<[u8; 32]>, hello: Hello) -> Value {
    let (dev, host, e_i, e_r) = (bytes(1), bytes(2), bytes(3), bytes(4));
    let prologue = hello.to_bytes();
    let host_pub = x25519_public(&host);
    let mut i =
        Initiator::new_with_ephemeral(&prologue, &dev, &host_pub, psk.as_ref(), &e_i).unwrap();
    let mut r = Responder::new_with_ephemeral(&prologue, &host, psk.as_ref(), &e_r).unwrap();
    let m1 = i.write_first(b"").unwrap();
    let (rs, _) = r.read_first(&m1).unwrap();
    assert_eq!(rs, x25519_public(&dev));
    let p2 = br#"{"v":1,"host_name":"devbox","gateway_version":"0.1.0","server_version":"0.1.0"}"#;
    let (m2, mut rsess) = r.write_second(p2).unwrap();
    let (_, mut isess) = i.read_second(&m2).unwrap();

    let small = br#"{"jsonrpc":"2.0","id":1,"method":"ping","params":{}}"#.to_vec();
    let big: Vec<u8> = (0..70_000u32).map(|n| b'a' + (n % 26) as u8).collect();
    let i_small = isess.encrypt(&small).unwrap();
    let i_big = isess.encrypt(&big).unwrap();
    let r_small = rsess.encrypt(&small).unwrap();
    for f in i_small.iter().chain(&i_big) {
        rsess.decrypt(f).unwrap();
    }
    let enc = |v: &Vec<Vec<u8>>| v.iter().map(b64::encode).collect::<Vec<_>>();
    json!({
        "name": name,
        "pattern": if psk.is_some() { vk_e2e::noise::IK_PSK2 } else { vk_e2e::noise::IK },
        "prologue": String::from_utf8(prologue).unwrap(),
        "device_static_private": b64::encode(dev),
        "host_static_private": b64::encode(host),
        "host_static_public": b64::encode(host_pub),
        "initiator_ephemeral": b64::encode(e_i),
        "responder_ephemeral": b64::encode(e_r),
        "psk": psk.map(b64::encode),
        "msg1": b64::encode(&m1),
        "msg2": b64::encode(&m2),
        "msg2_payload": String::from_utf8(p2.to_vec()).unwrap(),
        "transport": {
            "small_plaintext": String::from_utf8(small).unwrap(),
            "big_plaintext_len": big.len(),
            "initiator_frames": [enc(&i_small), enc(&i_big)],
            "responder_frames": [enc(&r_small)],
        }
    })
}

#[test]
fn vectors() {
    let v = json!({
        "comment": "Generated by crates/vk-e2e/tests/vectors.rs. big plaintext = 70000 bytes of 'a'+(n%26).",
        "cases": [
            case("ik", None, Hello::device()),
            case("ikpsk2", Some(bytes(5)), Hello::pair("pid-1")),
        ],
        "keys": {
            "device_public": b64::encode(x25519_public(&bytes(1))),
            "device_fingerprint": vk_e2e::keys::fingerprint(&x25519_public(&bytes(1))),
            "relay_public_for_host_id": b64::encode(bytes(6)),
            "host_id": vk_e2e::keys::host_id(&bytes(6)),
        }
    });
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/vectors.json");
    let text = serde_json::to_string_pretty(&v).unwrap() + "\n";
    if std::env::var_os("VK_E2E_WRITE_VECTORS").is_some() {
        std::fs::write(&path, text).unwrap();
    } else {
        let existing = std::fs::read_to_string(&path)
            .expect("vectors.json missing; regenerate with VK_E2E_WRITE_VECTORS=1");
        assert_eq!(existing, text, "vectors changed; regenerate deliberately");
    }
}
