// Hand-written runtime of the Vibeke control-API client (spec 07 §1). The types come from
// `types.gen.ts`, generated by `VIBEKE_UPDATE_CLIENTS=1 cargo test -p vibeke --test api_clients`.
//
// Transport: JSON-RPC 2.0, one JSON object per line on the session's unix socket. Lines are
// split on "\n" only (U+2028/U+2029 are legal inside JSON strings). The connection is long-lived
// and multiplexed: requests are pipelined and correlated by id; event subscriptions share it.

import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import { API_VERSION } from "./types.gen.ts";
import type {
  Cursor,
  ErrorKind,
  MethodName,
  Methods,
  VibekeEvent,
} from "./types.gen.ts";

export const MAX_LINE_BYTES = 16 * 1024 * 1024;

/** An error response (`error.data.kind` is the stable machine-readable string, 07 §1.4). */
export class VibekeError extends Error {
  readonly code: number;
  readonly kind: ErrorKind | string;
  readonly details: unknown;
  readonly retryable: boolean;
  constructor(e: { code: number; message: string; data?: { kind?: string; details?: unknown; retryable?: boolean } }) {
    super(`${e.data?.kind ?? "error"}: ${e.message}`);
    this.name = "VibekeError";
    this.code = e.code;
    this.kind = e.data?.kind ?? "internal";
    this.details = e.data?.details;
    this.retryable = e.data?.retryable ?? false;
  }
}

/** The subscription's queue overflowed on the server: resubscribe with `after: resumeFrom`. */
export class EventOverflow extends Error {
  readonly resumeFrom: Cursor;
  constructor(resumeFrom: Cursor) {
    super("events.overflow: resubscribe from the resume cursor");
    this.name = "EventOverflow";
    this.resumeFrom = resumeFrom;
  }
}

export interface ConnectOptions {
  /** Socket path. Default: `$VIBEKE_SOCKET`, else the session's runtime dir. */
  socketPath?: string;
  /** Session name (default `$VIBEKE_SESSION`, else `default`). */
  session?: string;
  /** Pane token (default `$VIBEKE_PANE_TOKEN`): limits the connection to pane scope. */
  token?: string;
  /** Client name sent in `client.hello`. */
  client?: string;
  /** `client.hello` kind (default `plugin`). */
  kind?: "tui" | "cli" | "plugin" | "gateway" | "agent";
  /** Skip the handshake (the connection is then `anonymous`, 07 §1.1). */
  hello?: boolean;
  /**
   * Skip the socket ownership check (`checkSocketTrust`). Only for sockets you know are safe
   * despite failing it; the pane token and every request would otherwise go to whoever planted
   * the socket.
   */
  insecure?: boolean;
}

/** The runtime root: `$VIBEKE_RUNTIME_DIR`, `$XDG_RUNTIME_DIR/vibeke` or `$TMPDIR/vibeke-<uid>`. */
export function runtimeRoot(): string {
  if (process.env.VIBEKE_RUNTIME_DIR) return process.env.VIBEKE_RUNTIME_DIR;
  if (process.env.XDG_RUNTIME_DIR) return path.join(process.env.XDG_RUNTIME_DIR, "vibeke");
  return path.join(process.env.TMPDIR || "/tmp", `vibeke-${os.userInfo().uid}`);
}

/** The socket of a session: `$VIBEKE_RUNTIME_DIR/<session>/vibeke.sock` and its fallbacks. */
export function defaultSocketPath(session = process.env.VIBEKE_SESSION || "default"): string {
  const explicit = process.env.VIBEKE_SOCKET;
  if (explicit && (process.env.VIBEKE_SESSION || "default") === session) return explicit;
  return path.join(runtimeRoot(), session, "vibeke.sock");
}

/** `checkSocketTrust` refused a socket: nothing was sent to it. */
export class SocketTrustError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SocketTrustError";
  }
}

export interface SocketTrustOptions {
  /** Runtime root (default `runtimeRoot()`). */
  root?: string;
  /** Expected owner (default: the effective uid). */
  uid?: number;
}

function lstatOrNull(p: string): fs.Stats | null {
  try {
    return fs.lstatSync(p);
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw new SocketTrustError(`cannot inspect ${p}: ${(e as Error).message}`);
  }
}

/**
 * Refuse a socket whose directory chain or file could have been planted by another user (an
 * attacker-created `/tmp/vibeke-<uid>` symlink or directory, say), as the CLI does
 * (`check_socket_trust`). Under the runtime root every directory from the socket's up to the
 * root must be a real directory (never followed through a symlink) owned by `uid` with mode
 * 0700; for an explicit socket elsewhere its parent must be a real directory owned by `uid`
 * and not group- or world-writable. The socket must be a socket owned by `uid`. Missing pieces
 * pass (the connect then fails by itself). Throws `SocketTrustError`.
 */
export function checkSocketTrust(socket: string, opts: SocketTrustOptions = {}): void {
  const uid = opts.uid ?? (process.geteuid ? process.geteuid() : os.userInfo().uid);
  const sock = path.resolve(socket);
  const root = path.resolve(opts.root ?? runtimeRoot());
  const parent = path.dirname(sock);
  if (parent === sock) throw new SocketTrustError(`socket path ${socket} has no parent directory`);
  const rel = path.relative(root, sock);
  const underRoot = rel !== "" && !rel.startsWith("..") && !path.isAbsolute(rel);
  const dirs: [string, boolean][] = [];
  if (underRoot) {
    for (let d = parent; ; d = path.dirname(d)) {
      dirs.push([d, true]);
      if (d === root || path.dirname(d) === d) break;
    }
  } else dirs.push([parent, false]);
  for (const [d, strict] of dirs) {
    const st = lstatOrNull(d);
    if (!st) return;
    if (st.isSymbolicLink() || !st.isDirectory()) {
      throw new SocketTrustError(`refusing ${socket}: ${d} is not a plain directory (symlink or other file)`);
    }
    if (st.uid !== uid) throw new SocketTrustError(`refusing ${socket}: ${d} is owned by uid ${st.uid}, not ${uid}`);
    const mode = st.mode & 0o7777;
    if ((strict && mode !== 0o700) || (!strict && (mode & 0o022) !== 0)) {
      throw new SocketTrustError(
        `refusing ${socket}: ${d} has mode ${mode.toString(8)}${strict ? " (need 700)" : ""}`,
      );
    }
  }
  const st = lstatOrNull(sock);
  if (!st) return;
  if (!st.isSocket()) throw new SocketTrustError(`refusing ${socket}: not a socket`);
  if (st.uid !== uid) throw new SocketTrustError(`refusing ${socket}: socket is owned by uid ${st.uid}, not ${uid}`);
}

export interface EventOptions {
  /** Glob patterns, e.g. `["agent.*", "pane.{created,closed}"]`. Default: every type. */
  types?: string[];
  /** Resume after a cursor (or a bare `seq` for local scripts). Default: live events only. */
  after?: Cursor | number;
  subjects?: { workspace?: string; tab?: string; pane?: string; run?: string; task?: string };
}

/** A subscription: an async iterator of events, ended by `close()` or a closed connection. */
export class EventStream implements AsyncIterable<VibekeEvent> {
  readonly subscriptionId: string;
  /** The log position at subscription time. */
  readonly at: Cursor;
  private queue: VibekeEvent[] = [];
  private waiter: ((r: IteratorResult<VibekeEvent>) => void) | null = null;
  private failer: ((e: unknown) => void) | null = null;
  private done = false;
  private error: unknown = null;
  private readonly onClose: () => void;

  constructor(subscriptionId: string, at: Cursor, onClose: () => void) {
    this.subscriptionId = subscriptionId;
    this.at = at;
    this.onClose = onClose;
  }

  /** @internal */
  push(e: VibekeEvent): void {
    if (this.done) return;
    if (this.waiter) {
      const w = this.waiter;
      this.waiter = this.failer = null;
      w({ value: e, done: false });
    } else this.queue.push(e);
  }

  /** @internal */
  end(error?: unknown): void {
    if (this.done) return;
    this.done = true;
    this.error = error ?? null;
    if (this.waiter && this.failer) {
      const [w, f] = [this.waiter, this.failer];
      this.waiter = this.failer = null;
      if (error) f(error);
      else w({ value: undefined, done: true });
    }
  }

  /** @internal Events queued and not yet consumed. */
  get queued(): number {
    return this.queue.length;
  }

  /**
   * Stop delivering events (events already queued are dropped) and end the server-side
   * subscription (`events.unsubscribe`, best effort). Later events for it are discarded.
   */
  close(): void {
    this.queue = [];
    this.end();
    this.onClose();
  }

  [Symbol.asyncIterator](): AsyncIterator<VibekeEvent> {
    return {
      next: () => {
        const e = this.queue.shift();
        if (e) return Promise.resolve({ value: e, done: false });
        if (this.done) {
          if (this.error) {
            const err = this.error;
            this.error = null;
            return Promise.reject(err);
          }
          return Promise.resolve({ value: undefined, done: true });
        }
        return new Promise((resolve, reject) => {
          this.waiter = resolve;
          this.failer = reject;
        });
      },
      return: () => {
        this.close();
        return Promise.resolve({ value: undefined, done: true });
      },
    };
  }
}

interface Pending {
  resolve: (v: unknown) => void;
  reject: (e: unknown) => void;
  timer?: NodeJS.Timeout;
  /** Runs synchronously while the response line is handled (before any later line). */
  onResult?: (v: unknown) => unknown;
}

export class VibekeClient {
  private readonly socket: net.Socket;
  private nextId = 1;
  private readonly pending = new Map<number, Pending>();
  // Live subscriptions. A stream is registered while its subscribe response line is handled,
  // so pushes (and an overflow) that follow it in the same chunk find it; pushes for any other
  // id (a closed stream, a stranger) are dropped, never buffered.
  private readonly streams = new Map<string, EventStream>();
  private buf: Buffer = Buffer.alloc(0);
  private closed: Error | null = null;
  /** The `client.hello` result, when the handshake ran. */
  hello: Methods["client.hello"]["result"] | null = null;

  private constructor(socket: net.Socket) {
    this.socket = socket;
    socket.on("data", (d) => this.onData(d));
    socket.on("error", (e) => this.fail(e));
    socket.on("close", () => this.fail(new Error("connection closed")));
  }

  static async connect(opts: ConnectOptions = {}): Promise<VibekeClient> {
    const session = opts.session ?? (process.env.VIBEKE_SESSION || "default");
    const p = opts.socketPath ?? defaultSocketPath(session);
    // Before connecting: a planted socket gets neither a connection nor a byte.
    if (!opts.insecure) checkSocketTrust(p);
    const socket = net.createConnection(p);
    await new Promise<void>((resolve, reject) => {
      socket.once("connect", resolve);
      socket.once("error", reject);
    });
    const c = new VibekeClient(socket);
    if (opts.hello !== false) {
      c.hello = await c.call("client.hello", {
        client: opts.client ?? "vibeke-client-ts",
        version: "0.1.0",
        api: API_VERSION,
        kind: opts.kind ?? "plugin",
        token: opts.token ?? process.env.VIBEKE_PANE_TOKEN ?? "",
      });
    }
    return c;
  }

  /** Call a method; resolves with the typed result or rejects with a `VibekeError`. */
  call<M extends MethodName>(
    method: M,
    params: Methods[M]["params"],
    opts: { timeoutMs?: number } = {},
  ): Promise<Methods[M]["result"]> {
    return this.request(method, params, opts) as Promise<Methods[M]["result"]>;
  }

  private request(
    method: string,
    params: unknown,
    opts: { timeoutMs?: number } = {},
    onResult?: (v: unknown) => unknown,
  ): Promise<unknown> {
    if (this.closed) return Promise.reject(this.closed);
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      const p: Pending = { resolve, reject, onResult };
      if (opts.timeoutMs) {
        p.timer = setTimeout(() => {
          this.pending.delete(id);
          reject(new Error(`${method}: no response within ${opts.timeoutMs} ms`));
        }, opts.timeoutMs);
      }
      this.pending.set(id, p);
      this.socket.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n", (err) => {
        if (err) {
          this.pending.delete(id);
          reject(err);
        }
      });
    });
  }

  /** Subscribe to events (`events.subscribe`) and iterate them with `for await`. */
  async events(opts: EventOptions = {}): Promise<EventStream> {
    const params: Methods["events.subscribe"]["params"] = {};
    if (opts.types) params.types = opts.types;
    if (opts.after !== undefined) params.after = opts.after;
    if (opts.subjects) params.subjects = opts.subjects;
    const stream = (await this.request("events.subscribe", params, {}, (v) => {
      const r = v as Methods["events.subscribe"]["result"];
      const id = r.subscription_id;
      const s = new EventStream(id, r.at, () => this.unsubscribe(id));
      this.streams.set(id, s);
      return s;
    })) as EventStream;
    if (this.closed) stream.end();
    return stream;
  }

  private unsubscribe(id: string): void {
    // Not registered any more (overflowed, or the connection ended): nothing to stop.
    if (!this.streams.delete(id) || this.closed) return;
    this.request("events.unsubscribe", { subscription_id: id }, { timeoutMs: 10_000 }).catch(() => {});
  }

  /** @internal Live streams and the events they hold (tests: retention stays bounded). */
  retained(): { streams: number; events: number } {
    let events = 0;
    for (const s of this.streams.values()) events += s.queued;
    return { streams: this.streams.size, events };
  }

  /** Close the connection; pending calls reject and event streams end. */
  close(): void {
    this.socket.destroy();
    this.fail(new Error("connection closed"));
  }

  private onData(d: Buffer): void {
    this.buf = this.buf.length ? Buffer.concat([this.buf, d]) : d;
    for (;;) {
      const nl = this.buf.indexOf(0x0a);
      if (nl < 0) break;
      const line = this.buf.subarray(0, nl).toString("utf8");
      this.buf = this.buf.subarray(nl + 1);
      if (line.trim()) this.onLine(line);
    }
    if (this.buf.length > MAX_LINE_BYTES) this.fail(new Error("line exceeds 16 MiB"));
  }

  private onLine(line: string): void {
    let m: any;
    try {
      m = JSON.parse(line);
    } catch {
      return; // not ours to fail on: servers only send JSON
    }
    if (m.id !== undefined && m.id !== null && (m.result !== undefined || m.error !== undefined)) {
      const p = this.pending.get(m.id);
      if (!p) return;
      this.pending.delete(m.id);
      if (p.timer) clearTimeout(p.timer);
      if (m.error) p.reject(new VibekeError(m.error));
      else if (p.onResult) {
        try {
          p.resolve(p.onResult(m.result));
        } catch (e) {
          p.reject(e);
        }
      } else p.resolve(m.result);
      return;
    }
    if (m.method === "events.event") {
      // Unknown ids (closed streams) are dropped.
      this.streams.get(m.params?.subscription_id)?.push(m.params.event);
    } else if (m.method === "events.overflow") {
      const s = this.streams.get(m.params.subscription_id);
      if (s) {
        this.streams.delete(m.params.subscription_id);
        s.end(new EventOverflow(m.params.resume_from));
      }
    }
    // Unknown notifications are ignored (07 §1.5).
  }

  private fail(e: Error): void {
    if (this.closed) return;
    this.closed = e;
    for (const p of this.pending.values()) {
      if (p.timer) clearTimeout(p.timer);
      p.reject(e);
    }
    this.pending.clear();
    for (const s of this.streams.values()) s.end();
    this.streams.clear();
  }
}
