[package]
name = "vk-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vk-proto = { workspace = true }
unicode-width = { workspace = true }
unicode-segmentation = { workspace = true }
base64 = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
