import { expect, test } from '@playwright/test'
import { docManifest } from '../content/manifest'

test('app screenshots rotate, enlarge, and support keyboard navigation', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Run your agents')
  await page.evaluate(() => document.fonts.ready)
  const showcase = page.getByRole('region', { name: 'Vibeke screenshots' })
  const orbit = showcase.locator('.client-orbit')
  await expect(orbit).toHaveAttribute('data-active-client', 'electron')
  await expect.poll(() => orbit.locator('img').evaluateAll(images => images.every(image => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
  await expect(orbit.locator('img')).toHaveCount(3)
  for (const [label, client] of [['Terminal', 'tui'], ['Browser', 'web'], ['Desktop', 'electron']]) {
    await showcase.getByRole('tab', { name: label, exact: true }).click()
    await expect(orbit).toHaveAttribute('data-active-client', client!)
    await expect(orbit.locator(`[data-client="${client}"]`)).toHaveAttribute('data-position', 'front')
    const stage = await orbit.boundingBox()
    const frame = await orbit.locator('[data-position="front"]').boundingBox()
    expect(frame!.y).toBeGreaterThanOrEqual(stage!.y)
    expect(frame!.y + frame!.height).toBeLessThanOrEqual(stage!.y + stage!.height + 1)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await showcase.screenshot({ path: `test-results/showcase-${client}-${info.project.name}.png` })
  }
  const desktop = showcase.getByRole('tab', { name: 'Desktop', exact: true })
  await desktop.press('ArrowRight')
  await expect(showcase.getByRole('tab', { name: 'Browser', exact: true })).toBeFocused()
  await expect(orbit).toHaveAttribute('data-active-client', 'web')
  await page.keyboard.press('Home')
  await expect(orbit).toHaveAttribute('data-active-client', 'tui')
  const enlarge = showcase.getByRole('button', { name: 'View full size' })
  await enlarge.click()
  const dialog = page.getByRole('dialog', { name: 'TUI', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('img')).toHaveAttribute('src', '/screenshots/tui.png')
  await expect(dialog.getByRole('button', { name: 'Close screenshot' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(enlarge).toBeFocused()
  await desktop.click()
  await orbit.getByRole('button', { name: 'Enlarge Electron app screenshot' }).click()
  await expect(page.getByRole('dialog', { name: 'Electron app', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close screenshot' }).click()
  // The site honors reduced-motion settings for the perspective transition.
  expect(await orbit.locator('[data-position="front"]').evaluate(element => getComputedStyle(element).transitionDuration)).toBe('0s')
  await page.getByRole('button', { name: 'Remote', exact: true }).click()
  await expect(page.getByText('Connect to a remote host.')).toBeVisible()
  await page.getByRole('button', { name: 'Local', exact: true }).click()
  await expect(page.getByText('Start a workspace.', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: `test-results/home-${info.project.name}.png`, fullPage: true })
})

test('search supports keyboard navigation, empty results, and deep links', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Search documentation' }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await page.getByRole('textbox', { name: 'Search documentation' }).fill('no-such-doc-zzzzz')
  await expect(dialog.getByText(/No matches/)).toBeVisible()
  await page.getByRole('textbox', { name: 'Search documentation' }).fill('configuration')
  await page.getByRole('textbox', { name: 'Search documentation' }).press('Enter')
  await expect(page).toHaveURL('/docs/config')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Configuration')
  await expect(dialog).not.toBeVisible()
  await page.keyboard.press('Control+k')
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
})

test('comparison matrix filters columns and scrolls on mobile without losing row labels', async ({ page }, info) => {
  await page.goto('/compare')
  const table = page.getByRole('table', { name: 'Vibeke and alternatives:' })
  await expect(table).toHaveCount(1)
  await expect(table.getByRole('columnheader')).toHaveCount(11)
  await expect(page.getByRole('table')).toHaveCount(1)
  await expect(table.locator('th[scope="row"]')).toHaveCount(29)
  await page.getByRole('button', { name: 'Agent apps' }).click()
  await expect(table.getByRole('columnheader')).toHaveCount(7)
  await expect(table.getByRole('columnheader', { name: 'Warp' })).toBeVisible()
  await expect(table.getByRole('columnheader', { name: 'Vibeke' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Conductor documentation' })).toHaveAttribute('href', 'https://www.conductor.build/docs')
  await page.getByRole('button', { name: 'Terminal tools' }).click()
  await expect(table.getByRole('columnheader')).toHaveCount(6)
  await page.getByRole('button', { name: 'All tools' }).click()
  if (info.project.name === 'mobile') {
    const region = page.getByRole('region', { name: 'Product comparison table' })
    await table.getByRole('columnheader').first().scrollIntoViewIfNeeded()
    const label = table.getByRole('rowheader', { name: 'Details: Client disconnect' })
    const before = await label.boundingBox()
    await region.evaluate(element => { element.scrollLeft = element.scrollWidth })
    expect(await region.evaluate(element => element.scrollLeft)).toBeGreaterThan(0)
    const after = await label.boundingBox()
    expect(after?.x).toBeCloseTo(before!.x, 0)
    await expect(table.getByRole('columnheader', { name: 'Superset' })).toBeInViewport()
    await region.evaluate(element => { element.scrollLeft = 0 })
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `test-results/compare-${info.project.name}.png`, fullPage: true })
})

test('one comparison table filters features and links every product to its source', async ({ page }) => {
  await page.goto('/compare')
  const table = page.getByRole('table', { name: 'Vibeke and alternatives: feature comparison' })
  await expect(page.getByRole('table')).toHaveCount(1)
  await expect(table.getByRole('columnheader')).toHaveCount(11)
  await expect(table.getByRole('row', { name: /Transfer work to a teammate/ })).toContainText('Yes')
  await expect(table.getByRole('row', { name: /Move work between hosts/ }).getByRole('cell').nth(1)).toHaveText('No')
  await expect(table.getByRole('row', { name: /Access without inbound ports/ }).getByRole('cell').nth(1)).toHaveText('No')
  await page.getByRole('button', { name: 'Browser', exact: true }).click()
  await expect(table.locator('th[scope="row"]')).toHaveCount(5)
  await expect(table.getByRole('columnheader')).toHaveCount(11)
  await expect(table.getByRole('row', { name: /Transfer work to a teammate/ })).toHaveCount(0)
  await expect(table.getByRole('row', { name: /Human browser control/ })).toContainText('Take over')
  await table.getByRole('button', { name: 'Details: Agent browser control', exact: true }).click()
  const details = page.getByRole('region', { name: 'Agent browser control details', exact: true })
  const box = await details.boundingBox()
  expect(box!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await expect(table.getByRole('link', { name: 'Herdr source: Agent browser control' })).toHaveAttribute('href', 'https://herdr.dev/docs/socket-api/')
  await expect(table.getByRole('link', { name: 'cmux source: Agent browser control' })).toHaveAttribute('href', 'https://cmux.com/docs/browser-automation')
  await expect(table.getByRole('link', { name: 'Warp source: Agent browser control' })).toHaveAttribute('href', 'https://docs.warp.dev/agents/capabilities/computer-use/browser-use/')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Machines and teams', exact: true }).click()
  await table.getByRole('button', { name: 'Details: Transfer work to a teammate', exact: true }).click()
  await table.getByRole('link', { name: 'Vibeke source: Transfer work to a teammate' }).click()
  await expect(page).toHaveURL('/docs/handoff')
  await expect(page.locator('article')).toContainText('is never imported automatically')
  await expect(page.locator('article')).toContainText('decides whether to resume the agent')
})

test('all documentation routes render directly without broken local links or overflow', async ({ page }, info) => {
  for (const doc of docManifest) {
    const response = await page.goto(`/docs/${doc.slug}`)
    expect(response?.status()).toBe(200)
    await expect(page.getByRole('heading', { level: 1 })).toHaveText(doc.title)
    await expect(page.locator('article')).not.toContainText('{{#include')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const missingAnchors = await page.locator('nav[aria-label="On this page"] a').evaluateAll(links => links.filter(link => !document.getElementById(decodeURIComponent((link as HTMLAnchorElement).hash.slice(1)))).map(link => link.textContent))
    expect(missingAnchors).toEqual([])
  }
  await page.goto('/docs/quickstart')
  await page.screenshot({ path: `test-results/docs-${info.project.name}.png`, fullPage: true })
})

test('copy controls and mobile navigation work', async ({ page }, info) => {
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/docs/quickstart')
  await page.getByRole('button', { name: 'Copy code', exact: true }).first().click()
  await expect(page.getByRole('button', { name: 'Copied', exact: true })).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('cd your-project\nvibeke')
  if (info.project.name === 'mobile') {
    await page.getByRole('button', { name: 'Documentation menu' }).click()
    await page.getByRole('link', { name: 'Process durability', exact: true }).first().click()
    await expect(page).toHaveURL('/docs/holders')
    await page.getByRole('button', { name: 'Open navigation' }).click()
    await page.getByRole('navigation', { name: 'Mobile navigation' }).getByRole('link', { name: 'Compare' }).click()
    await expect(page).toHaveURL('/compare')
    await expect(page.getByRole('button', { name: 'Open navigation' })).toBeVisible()
  }
})

test('unknown documentation paths return an accessible 404', async ({ page }) => {
  const response = await page.goto('/docs/not-a-real-chapter')
  expect(response?.status()).toBe(404)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Page not found.')
  await expect(page.getByRole('link', { name: 'Open documentation' })).toBeVisible()
})


test('API methods filter, expand, and copy without breaking the table', async ({ page }, info) => {
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/docs/api')
  const table = page.getByRole('table', { name: 'API methods' })
  await expect(table.getByRole('columnheader')).toHaveCount(2)
  await expect(table.getByRole('rowheader')).toHaveCount(20)
  const search = page.getByRole('searchbox', { name: 'Find an API method' })
  await search.fill('browser.pane.update')
  const method = table.getByRole('button', { name: 'browser.pane.update' })
  await method.focus()
  await method.press('Enter')
  await expect(method).toHaveAttribute('aria-expanded', 'true')
  const details = page.getByRole('region', { name: 'browser.pane.update details' })
  await expect(details).toContainText('Parameters')
  await expect(details).toContainText('viewport')
  await details.getByRole('button', { name: 'Copy parameters' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('viewport')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await table.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: `test-results/api-${info.project.name}.png`, fullPage: true })
  await method.click()
  await expect(details).toHaveCount(0)
  await search.fill('does-not-exist')
  await expect(page.getByText('No methods match. Change the search or group.')).toBeVisible()
  await search.fill('')
  await page.getByRole('combobox', { name: 'Method group' }).selectOption('agent')
  for (const name of await table.getByRole('rowheader').allTextContents()) expect(name).toMatch(/^agent\./)
  const catalog = await page.request.get('/api-reference/methods.json')
  expect(catalog.status()).toBe(200)
  expect((await catalog.json()).methods.length).toBeGreaterThan(200)
  const schema = await page.request.get('/api-reference/vibeke-1.schema.json')
  expect(schema.status()).toBe(200)
  expect((await schema.json()).$defs).toBeTruthy()
})


test('public install endpoint redirects to the release installer', async ({ request }) => {
  const response = await request.get('/install.sh', { maxRedirects: 0 })
  expect(response.status()).toBe(302)
  expect(response.headers().location).toBe('https://github.com/MidgardAI/vibeke/releases/latest/download/install.sh')
})

// Prerendered pages are static files: `vite preview` serves them without Nitro's route-rule
// headers, while the Vercel output applies the rules to them. Check the deployed site only.
test('pages carry the baseline security headers', async ({ request }) => {
  test.skip(!process.env.PLAYWRIGHT_BASE_URL, 'headers are applied by the Vercel output, not the preview server')
  const response = await request.get('/')
  const headers = response.headers()
  expect(headers['x-frame-options']).toBe('DENY')
  expect(headers['content-security-policy']).toContain("frame-ancestors 'none'")
  expect(headers['x-content-type-options']).toBe('nosniff')
  expect(headers['referrer-policy']).toBe('strict-origin-when-cross-origin')
})
